[minor change] dhcp labels
ciscoecosystem/mso-go-client pull request #104
Opened 2022-11-04 15:03 UTC by akinross

2022-11-04 17:50 UTC, lhercot requested changes

2022-11-04 17:50 UTC, lhercot commented on models/model.go
> +type patchPayload struct {
PatchPayload

2022-11-04 17:50 UTC, lhercot commented on models/schema_template_bd.go
>  }
Make generic and move to models file.

2022-11-07 04:14 UTC, sajagana commented on models/model.go
> +func GetRemovePatchPayload(path string) *PatchPayload {
I couldn’t understand the usage of GetRemovePatchPayload. Can we use a meaningful name?

2022-11-07 07:22 UTC, sajagana approved these changes
LGTM!

2022-11-07 16:04 UTC, lhercot approved these changes
LGTM

2022-11-07 16:05 UTC, merged