Add schema site contract model
ciscoecosystem/mso-go-client pull request #112
Opened 2023-04-21 16:44 UTC by danischm

2023-04-24 09:19 UTC, lhercot requested changes

2023-04-24 09:19 UTC, lhercot commented on models/schema_site_contract.go
> +	return &SiteContract{
We moved to a generic version of PatchPayload in the latest code so if you can use this going forward.

```suggestion
	return & PatchPayload{
```

2023-04-24 09:19 UTC, lhercot commented on models/schema_site_contract.go
> +}
```suggestion
```

2023-04-24 09:19 UTC, lhercot commented on models/schema_site_contract.go
> +}
```suggestion
```

2025-07-17 07:57 UTC, closed without merging

2025-07-17 07:57 UTC, akinross commented
as agreed closing