Added SiteContractServiceGraphListener structure to manage the Azure CNC listeners
ciscoecosystem/mso-go-client pull request #129
Opened 2023-11-24 14:35 UTC by sajagana

Note:

Added SiteContractServiceGraphListener structure to schema_template_contract_service_graph.go, model.

2023-11-25 14:07 UTC, akinross requested changes

2023-11-25 14:07 UTC, akinross commented on models/schema_template_contract_service_graph.go
> +type SiteContractServiceGraphListener struct {
Why not leverage PatchPayloadList in model.go?

2023-11-25 14:07 UTC, akinross commented on models/schema_template_contract_service_graph.go
> +func (listenerAttr *SiteContractServiceGraphListener) ToMap() (map[string]interface{}, error) {
When PatchPayloadList is leverage it's ToMap() function can be used.

2023-11-25 14:07 UTC, akinross commented on models/schema_template_contract_service_graph.go
> +}
```suggestion
func NewSiteContractServiceGraphListener(ops, path, name, protocol, securityPolicy string, port int, certificates []interface{}, rules []interface{}, frontendIpDnMap map[string]string) *PatchPayloadList {
	var listenerMap map[string]interface{}
	if ops != "remove" {
		listenerMap = map[string]interface{}{
			"name":         name,
			"port":         port,
			"protocol":     protocol,
			"secPolicy":    securityPolicy,
			"certificates": certificates,
			"rules":        rules,
			"nlbDevIp":     frontendIpDnMap,
		}
	}

	return &PatchPayloadList{
		Ops:   ops,
		Path:  path,
		Value: listenerMap,
	}
}
```

2023-11-25 14:07 UTC, akinross commented on models/schema_template_contract_service_graph.go
> +}
```suggestion
```

2023-11-25 14:07 UTC, akinross commented on models/schema_template_contract_service_graph.go
> +}
```suggestion
```

2023-11-25 14:08 UTC, akinross commented on models/schema_template_contract_service_graph.go
> +	if ops != "remove" {
I don't think this check is needed when you will use, GetRemovePatchPayload in the resource.

2023-11-27 11:10 UTC, akinross approved these changes
LGTM

2023-11-27 22:00 UTC, lhercot approved these changes
LGTM

2023-11-27 22:00 UTC, merged